name: yocto minimal

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - run: echo "yocto minimal"
    - uses: actions/checkout@v3
    - name: Fetch dependency
      run: sudo apt install build-essential chrpath gawk git bmap-tools texinfo diffstat
    - name: Create build folder
      run: |
        mkdir -p /portable/yocto/kirkstone
        mkdir /portable/yocto/kirkstone/builds
        mkdir /portable/yocto/kirkstone/downloads
        cd /portable/yocto/kirkstone
    - name: Clone yocto
      run: git clone -b kirkstone git://git.yoctoproject.org/poky.git
      
