name: yocto minimal

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - run: echo "yocto minimal"
    - uses: actions/checkout@v3
    - name: Fetch dependency
      run: sudo apt install build-essential chrpath gawk git bmap-tools texinfo diffstat tree zstd liblz4-tool chrpath diffstat
    - name: Set build env
      run: echo "CUR_DIR=$(pwd)" >> "$GITHUB_ENV"
    - name: Create build folder
      run: |
        mkdir -p $CUR_DIR/portable/yocto/kirkstone
        mkdir $CUR_DIR/portable/yocto/kirkstone/builds
        mkdir $CUR_DIR/portable/yocto/kirkstone/downloads
    - name: Clone yocto
      run: git clone -b kirkstone git://git.yoctoproject.org/poky.git $CUR_DIR/portable/yocto/kirkstone/poky
    - name: Clone meta-rasp
      run: git clone -b kirkstone https://github.com/agherzan/meta-raspberrypi.git $CUR_DIR/portable/yocto/kirkstone/meta-raspberrypi
    - name: Clone meta-openembedded
      run: git clone -b kirkstone git://git.openembedded.org/meta-openembedded $CUR_DIR/portable/yocto/kirkstone/meta-openembedded
    - name: Set build env
      run: |
        source $CUR_DIR/portable/yocto/kirkstone/poky/oe-init-build-env $CUR_DIR/portable/yocto/kirkstone/builds/rpi
        bitbake-layers -h
        bitbake-layers add-layer \
         	$CUR_DIR/portable/yocto/kirkstone/meta-openembedded/meta-oe \
         	$CUR_DIR/portable/yocto/kirkstone/meta-openembedded/meta-multimedia \
         	$CUR_DIR/portable/yocto/kirkstone/meta-openembedded/meta-networking \
         	$CUR_DIR/portable/yocto/kirkstone/meta-openembedded/meta-python \
         	$CUR_DIR/portable/yocto/kirkstone/meta-raspberrypi 
          sed -i '/MACHINE/d' $CUR_DIR/portable/yocto/kirkstone/builds/rpi/conf/local.conf
          sed -i '1i\MACHINE = "raspberrypi4-64"' $CUR_DIR/portable/yocto/kirkstone/builds/rpi/conf/local.conf
          export DL_DIR="$CUR_DIR/portable/yocto/kirkstone/downloads"
          bitbake core-image-minimal
    - name: Check image output
      run: ls -al $CUR_DIR/portable/yocto/kirkstone/builds/rpi/tmp/deploy/images/raspberrypi3/core-image-minimal*

