name: yocto minimal

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - run: echo "yocto minimal"
    - uses: actions/checkout@v3
    - name: Fetch dependency
      run: sudo apt install build-essential chrpath gawk git bmap-tools texinfo diffstat
    - name: Create build folder
      run: |
        mkdir -p ~/portable/yocto/kirkstone
        mkdir ~/portable/yocto/kirkstone/builds
        mkdir ~/portable/yocto/kirkstone/downloads
        cd ~/portable/yocto/kirkstone
    - name: Clone yocto
      run: git clone -b kirkstone git://git.yoctoproject.org/poky.git
    - name: Clone meta-rasp
      run: git clone -b kirkstone https://github.com/agherzan/meta-raspberrypi.git
    - name: Clone meta-openembedded
      run: git clone -b kirkstone git://git.openembedded.org/meta-openembedded

    - name: debug-checkoutput
      run: ls -al ~/portable/yocto/kirkstone/poky/
    - name: Set build env
      run: source ~/portable/yocto/kirkstone/poky/oe-init-build-env ~/portable/yocto/kirkstone/builds/rpi
    - name: Install zstd (dependency)
      run: sudo apt install -y zstd liblz4-tool chrpath diffstat
    - name: Update meta layer
      run: |
        bitbake-layers -h
        bitbake-layers add-layer \
        	/portable/yocto/kirkstone/meta-openembedded/meta-oe \
         	/portable/yocto/kirkstone/meta-openembedded/meta-multimedia \
         	/portable/yocto/kirkstone/meta-openembedded/meta-networking \
         	/portable/yocto/kirkstone/meta-openembedded/meta-python \
         	/portable/yocto/kirkstone/meta-raspberrypi 
    - name: Update machine name to raspberrypi4-64
      run: |
          sed -i '/MACHINE/d' ~/portable/yocto/kirkstone/builds/rpi/conf/local.conf
          sed -i '1i\MACHINE = "raspberrypi4-64"' ~/portable/yocto/kirkstone/builds/rpi/conf/local.conf
          export DL_DIR="~/portable/yocto/kirkstone/downloads"
    - name: Build minimal image
      run: bitbake core-image-minimal
    - name: Check image output
      run: ls -al ~/portable/yocto/kirkstone/builds/rpi/tmp/deploy/images/raspberrypi3/core-image-minimal*

